### ISSUE TITLE
Outdated numbers and date of release of the MLE book :-)

### ISSUE THREAD

**Issue by K-miy** [True-Positive-Inc/Our-Stuff#2]
As it is your work anniversary on Linkedin, you may want to updates the number of your subscribers on the AI newletter 😉 
As of today it is over 250K 👍 

You may also want to update the relaease of the MLE book 😄

**Comment by aburkov** [comment]
> As it is your work anniversary on Linkedin, you may want to updates the number of your subscribers on the AI newletter 😉
> As of today it is over 250K 👍
> 
> You may also want to update the relaease of the MLE book 😄

Merci, Camille, updated!
